import{a as y,S as g,i as L}from"./assets/vendor-JxvvEPkb.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const b="https://pixabay.com/api/",w="45854856-78ad068c46767c3f7b48e1998",v=15,P=async(t,e=1)=>{try{return(await y.get(`${b}`,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:v}})).data}catch(s){console.error("Error fetching images:",s)}},u=document.querySelector(".gallery"),S=new g(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.8}),q=t=>t.map(({largeImageURL:e,webformatURL:s,tags:i,likes:r,views:o,comments:a,downloads:h})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e}">
          <img class="gallery-image" src="${s}" alt="${i}" loading="lazy" />
        </a>
        <div class="info">
          <p class="text-info">Likes: <span class="number-info">${r}</span></p>
          <p class="text-info">Views: <span class="number-info">${o}</span></p>
          <p class="text-info">Comments: <span class="number-info">${a}</span></p>
          <p class="text-info">Downloads: <span class="number-info">${h}</span></p>
        </div>
      </li>`).join(""),x=(t,e=!1)=>{e&&(u.innerHTML="");const s=q(t);u.insertAdjacentHTML("beforeend",s),S.refresh()},c=(t,e="error")=>{L[e]({message:t,position:"topRight"})},M=document.querySelector(".search-form"),l=document.querySelector(".load-more"),p=document.querySelector(".loader");let n=1,f="",d=0;const $=()=>{p.classList.remove("hidden")},E=()=>{p.classList.add("hidden")},O=async t=>{t.preventDefault();const e=t.target.elements.input.value.trim();if(!e){c("Please enter a valid search query","error");return}f=e,n=1,await m(e,n)},m=async(t,e)=>{$();try{const s=await P(t,e);if(d=s.totalHits,d===0){c("No images found. Please try again!","error"),l.classList.add("hidden");return}x(s.hits,e===1),B()}catch{c("Something went wrong. Please try again later.","error")}finally{E()}},B=()=>{const t=Math.ceil(d/15);n>=t?(l.classList.add("hidden"),c("We're sorry, but you've reached the end of search results.","info")):l.classList.remove("hidden")},H=async()=>{n++,await m(f,n),I()},I=()=>{const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})};M.addEventListener("submit",O);l.addEventListener("click",H);
//# sourceMappingURL=index.js.map
